import type { Locale } from "../config";

export type AgentGuardCopy = {
  meta:{title:string;description:string};hero:{eyebrow:string;title:string;body:string;primary:string;secondary:string};
  runtime:{eyebrow:string;title:string;body:string;events:Array<{name:string;detail:string}>;decisions:string[];alert:string;resolution:string};
  chains:{eyebrow:string;title:string;body:string;items:Array<{title:string;body:string}>;fusion:string};
  capabilities:{eyebrow:string;title:string;items:Array<{title:string;body:string}>};
  layers:{eyebrow:string;title:string;items:Array<{index:string;title:string;body:string;items:string[]}>};
  deployment:{eyebrow:string;title:string;body:string;nodes:string[];modes:Array<{title:string;body:string}>};
  evidence:{eyebrow:string;title:string;body:string;items:Array<{title:string;body:string;label:string;href:string}>};
  cta:{title:string;body:string;primary:string;github:string};
};

export const agentguardCopy:Record<Locale,AgentGuardCopy>={
 en:{
  meta:{title:"AgentGuard — Full Runtime Security for AI Agents",description:"AgentGuard provides unified security control across AI agent reasoning, tool use, identity, data flow, evaluation, and operations."},
  hero:{eyebrow:"AGENTGUARD · ENTERPRISE AGENT SECURITY",title:"Security control for the full agent runtime.",body:"Observe, reason, and intervene before model calls, after reasoning, around tool execution, and across the data and identity boundaries that agents traverse.",primary:"Book a Demo",secondary:"View on GitHub"},
  runtime:{eyebrow:"RUNTIME CONTROL SURFACE",title:"Control risk at the moment it becomes actionable.",body:"AgentGuard connects to four critical runtime events and chooses the least disruptive control that preserves safe autonomy.",events:[{name:"Before LLM",detail:"Context, identity, intent, and policy boundary"},{name:"After LLM",detail:"Reasoning alignment and emerging action plan"},{name:"Before Tool",detail:"Permission, arguments, destination, and data scope"},{name:"After Tool",detail:"Result validation, lineage, and downstream exposure"}],decisions:["Allow","Correct","Approve","Redact","Limit","Block"],alert:"Sensitive dataset requested by an untrusted tool path",resolution:"Redact data · Limit scope · Continue safely"},
  chains:{eyebrow:"THREE-CHAIN INTELLIGENCE",title:"Reason across thought, behavior, and data—together.",body:"A risky action rarely has one cause. AgentGuard connects intent, multi-step behavior, tool context, and data lineage before it decides.",items:[{title:"Thought chain alignment",body:"Identify and correct high-risk reasoning before it becomes action."},{title:"Behavior chain reasoning",body:"Connect risk across steps, tools, agents, and delegated authority."},{title:"Data lineage tracking",body:"Trace sensitive data from source through use, transformation, and destination."}],fusion:"Deterministic DSL × Lightweight Safety Model × Frontier Model"},
  capabilities:{eyebrow:"CONTROL CAPABILITIES",title:"Security primitives for production agent systems.",items:[{title:"Framework runtime hooks",body:"Integrate controls at model and tool boundaries without rebuilding the agent."},{title:"Tool & MCP security proxy",body:"Inspect and govern tool calls, MCP traffic, arguments, and destinations."},{title:"Dynamic identity & permission",body:"Evaluate delegated authority against user, task, resource, and runtime context."},{title:"Trusted sandbox & network isolation",body:"Contain code, filesystem, process, and network activity inside explicit boundaries."},{title:"Automated red team & continuous evaluation",body:"Test the same policies and runtime surfaces that protect production agents."},{title:"Private control plane",body:"Keep policies, traces, evidence, and sensitive runtime data in your environment."}]},
  layers:{eyebrow:"ONE PLATFORM",title:"From secure connection to continuous improvement.",items:[{index:"01",title:"Secure Connect",body:"Connect agents, tools, models, identity, data, and sandbox boundaries.",items:["SDK / Hook","Sidecar","Gateway","MCP proxy"]},{index:"02",title:"Runtime Intelligence",body:"Understand trajectory risk and intervene with precise controls.",items:["Thought chain","Behavior chain","Data lineage","Decision engine"]},{index:"03",title:"Evaluate & Operate",body:"Continuously test, observe, investigate, and improve agent security.",items:["Red teaming","Evaluation","Risk profiles","Audit response"]},{index:"04",title:"Model & Data Foundation",body:"Turn research and deployment evidence into stronger safety intelligence.",items:["Data factory","Safety models","Risk knowledge","Feedback loop"]}]},
  deployment:{eyebrow:"ENTERPRISE ARCHITECTURE",title:"Deploy controls where your trust boundary lives.",body:"Use lightweight hooks for agent context, gateways for shared enforcement, and a private control plane for policy, evidence, and operations.",nodes:["Agent frameworks","SDK · Sidecar · Gateway","AgentGuard Runtime","Models · Tools · MCP · Data","Private Control Plane"],modes:[{title:"Application embedded",body:"SDK and runtime hooks provide detailed agent context."},{title:"Infrastructure enforced",body:"Sidecar and gateway modes centralize tool and data controls."},{title:"Privately operated",body:"Run the control plane and evidence store inside your environment."}]},
  evidence:{eyebrow:"VERIFIABLE EVIDENCE",title:"Built in the open where evidence is available.",body:"These links point to current public repositories, models, and research records. They are evidence paths—not fabricated deployment claims.",items:[{title:"AgentGuard repository",body:"Public runtime security project in the WhitzardAgent organization.",label:"Open GitHub",href:"https://github.com/WhitzardAgent/AgentGuard"},{title:"Safety models",body:"Thought-Aligner, MirrorGuard, ReasoningShield, IntentNet, and TrustNet appear in the public ecosystem metadata.",label:"Browse ecosystem",href:"/open-ecosystem"},{title:"Research record",body:"NVWA research assets preserve public papers, evaluation work, and source links.",label:"Read research",href:"/research"}]},
  cta:{title:"Put a security control layer around your agent runtime.",body:"Map AgentGuard to your agent frameworks, tools, MCP servers, identity system, data boundary, and deployment requirements.",primary:"Book a Demo",github:"View GitHub"}
 },
 zh:{
  meta:{title:"AgentGuard — 企业级智能体运行时安全平台",description:"AgentGuard 统一控制企业智能体的模型推理、工具调用、身份权限、数据流转、持续评测与安全运营。"},
  hero:{eyebrow:"AGENTGUARD · 企业级智能体安全",title:"覆盖智能体完整运行过程的统一安全控制层",body:"在模型调用前、推理生成后、工具执行前后，以及智能体跨越的数据和身份边界中，持续观察、判断并干预风险。",primary:"预约产品演示",secondary:"查看 GitHub"},
  runtime:{eyebrow:"运行时控制面",title:"在风险即将成为真实行动时精准介入",body:"AgentGuard 接入四类关键运行时事件，并选择对自主性干扰最小、又能满足安全边界的处置方式。",events:[{name:"模型调用前",detail:"上下文、身份、意图与策略边界"},{name:"模型调用后",detail:"推理校准与行动计划风险"},{name:"工具调用前",detail:"权限、参数、目标与数据范围"},{name:"工具调用后",detail:"结果校验、数据血缘与下游暴露"}],decisions:["允许","纠正","审批","脱敏","限制","阻断"],alert:"不可信工具路径请求访问敏感数据集",resolution:"脱敏数据 · 限制范围 · 安全继续"},
  chains:{eyebrow:"三链智能",title:"协同理解思维、行为和数据",body:"一次危险行动很少只有单一原因。AgentGuard 在处置前关联意图、多步行为、工具上下文和数据血缘。",items:[{title:"思维链实时校准",body:"在行动发生前识别并纠正高风险推理。"},{title:"行为链风险推理",body:"关联跨步骤、跨工具、跨智能体与委托权限的组合风险。"},{title:"数据链血缘追踪",body:"追踪敏感数据的来源、用途、变换过程和目标位置。"}],fusion:"确定性 DSL × 轻量安全模型 × 前沿大模型"},
  capabilities:{eyebrow:"控制能力",title:"面向生产级智能体系统的安全基础能力",items:[{title:"多框架运行时 Hook",body:"在模型和工具边界接入控制能力，无需重建智能体。"},{title:"工具与 MCP 安全代理",body:"检查并控制工具调用、MCP 流量、参数和目标位置。"},{title:"动态身份与权限",body:"结合用户、任务、资源和运行时上下文判断委托权限。"},{title:"可信沙箱与网络隔离",body:"将代码、文件、进程和网络活动限制在显式边界内。"},{title:"自动红队与持续评测",body:"持续测试保护生产智能体的策略与运行时控制面。"},{title:"私有企业控制面",body:"让策略、轨迹、证据与敏感运行数据留在企业环境中。"}]},
  layers:{eyebrow:"统一平台",title:"从安全接入到持续优化",items:[{index:"01",title:"安全接入",body:"连接智能体、工具、模型、身份、数据和沙箱边界。",items:["SDK / Hook","Sidecar","Gateway","MCP 代理"]},{index:"02",title:"智能防护",body:"理解轨迹风险，并通过精准处置干预。",items:["思维链","行为链","数据血缘","决策引擎"]},{index:"03",title:"评测运营",body:"持续测试、观察、调查并改进智能体安全。",items:["自动红队","持续评测","风险画像","审计响应"]},{index:"04",title:"模型底座",body:"将研究与部署证据转化为更强的安全智能。",items:["数据工厂","安全模型","风险知识","反馈闭环"]}]},
  deployment:{eyebrow:"企业架构",title:"在企业信任边界内部署控制能力",body:"用轻量 Hook 获取智能体上下文，用 Gateway 统一执行策略，用私有控制面管理规则、证据与安全运营。",nodes:["智能体框架","SDK · Sidecar · Gateway","AgentGuard Runtime","模型 · 工具 · MCP · 数据","私有控制面"],modes:[{title:"应用内嵌",body:"SDK 与运行时 Hook 提供完整智能体上下文。"},{title:"基础设施强制执行",body:"Sidecar 与 Gateway 统一控制工具和数据边界。"},{title:"私有化运营",body:"在企业环境内运行控制面和证据存储。"}]},
  evidence:{eyebrow:"可核实证据",title:"在能够公开验证的地方保持开放",body:"以下链接指向当前公开仓库、模型与研究记录，是可验证的能力路径，而非虚构部署案例。",items:[{title:"AgentGuard 开源仓库",body:"WhitzardAgent 组织公开的运行时安全项目。",label:"打开 GitHub",href:"https://github.com/WhitzardAgent/AgentGuard"},{title:"安全模型",body:"公开生态元数据包含 Thought-Aligner、MirrorGuard、ReasoningShield、IntentNet 与 TrustNet。",label:"浏览开放生态",href:"/zh/open-ecosystem"},{title:"研究记录",body:"NVWA 研究数据保留论文、评测工作与公开来源链接。",label:"查看研究",href:"/zh/research"}]},
  cta:{title:"为智能体完整运行过程建立统一安全控制层",body:"将 AgentGuard 映射到你的智能体框架、工具、MCP 服务、身份系统、数据边界与部署要求。",primary:"预约产品演示",github:"查看 GitHub"}
 }
};
